### ISSUE TITLE
Link is not correctly labeled

### ISSUE THREAD

**Issue by berkeleygamelab** [dlab-berkeley/git-fundamentals#18]
http://marklodato.github.io/visual-git-guide/index-en.html is labeled as "github " but it is git only

**Comment by davclark** [comment]
What section is that in?

**Comment by berkeleygamelab** [comment]
Awesome resources

Basic commands cheat sheet(s) (Note the links to other cheat sheets!)
Gamified git
GitHub sponsors this.
Where does "help" go from GitHub? Here.
@davclark is an awesome resource, himself! (when he's not being a jerk)
Linux commands cheat sheet (also mostly works for OS X command line).
git - the simple guide
The visual github guide

**Comment by davclark** [comment]
https://github.com/dlab-berkeley/git-fundamentals/blob/master/README.md

**Comment by berkeleygamelab** [comment]
https://github.com/dlab-berkeley/git-fundamentals#awesome-resources actually :)
