### ISSUE TITLE
Resurrect old list of resources from the history

### ISSUE THREAD

**Issue by davclark** [dlab-berkeley/git-fundamentals#22]
I actually did this during the Wednesday at Cornerstone live. But it should be easier to find.

**Comment by deniederhut** [comment]
@davclark is this still open?

**Comment by davclark** [comment]
I thought I did it, but I'll check

On Thu, Feb 4, 2016 at 11:34 AM, Dillon Niederhut <notifications@github.com>
wrote:

> @davclark <https://github.com/davclark> is this still open?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dlab-berkeley/git-fundamentals/issues/22#issuecomment-180016236>
> .
>



-- 
Dav Clark
Data Scientist
Berkeley D-Lab + BIDS
bead.glass
917-544-8408
